import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Glossary | APEX Protocol Docs",
    description: "Definitions for all APEX and DeFi terminology used throughout the documentation.",
};

const terms = [
    {
        term: "AMM (Automated Market Maker)",
        def: "The underlying protocol used by decentralized exchanges (like PancakeSwap) to trade assets without a traditional order book, using math formulas to price assets."
    },
    {
        term: "APEX Brain",
        def: "The autonomous, on-chain risk engine of the APEX protocol that measures live Impermanent Loss exposure and adjusts the reward split dynamically between growth and protection."
    },
    {
        term: "APEX-LP",
        def: "The ERC-4626 standard receipt token you receive when depositing USDC. It represents your proportional ownership of the entire vault."
    },
    {
        term: "APY (Annual Percentage Yield)",
        def: "The estimated annual rate of return an investment makes, taking into account the effect of compounding interest."
    },
    {
        term: "asBNB (Aster Liquid Staked BNB)",
        def: "A yield-bearing token generated by AsterDEX representing staked BNB. Its quantity remains stable, but its exchange price goes up relative to BNB as it accrues staking and airdrop rewards."
    },
    {
        term: "asUSDF",
        def: "A yield-bearing stablecoin generated by AsterDEX. It earns a steady delta-neutral yield (~3.6% APY). APEX uses this to build your protection buffer."
    },
    {
        term: "Blended APY",
        def: "The overall yield rate of the APEX vault, calculated as the weighted average of the high-yield asBNB staking strategy and the low-risk asUSDF buffer strategy."
    },
    {
        term: "Compound Bounty",
        def: "A strict 0.5% fee paid from successfully harvested yield to the wallet address that triggers the permissionless compound() function. This incentivizes a decentralized network of bots to maintain the protocol loop."
    },
    {
        term: "EVM (Ethereum Virtual Machine)",
        def: "The runtime environment for smart contracts on Ethereum and compatible chains (like the BNB Chain). This is where APEX records its permanent state."
    },
    {
        term: "Hedge Efficiency Score",
        def: "A permanent metric stored on-chain every cycle inside the HedgeSnapshot struct. It represents the ratio of your asUSDF protection buffer against your actual Impermanent Loss exposure in USDC terms."
    },
    {
        term: "HedgeSnapshot",
        def: "A struct written to the blockchain at the end of every APEX compound cycle containing the current timestamps, IL amount, buffer size, efficiency score, and latest brain logic splits."
    },
    {
        term: "Impermanent Loss (IL)",
        def: "The difference in value between providing liquidity in an automated market maker pool versus simply holding the same assets in a wallet. It occurs when token prices diverge from their entry point."
    },
    {
        term: "Non-Custodial",
        def: "A system design where users always maintain complete control over their funds. APEX has no access to user deposits; they are governed entirely by smart contracts."
    },
    {
        term: "Permissionless",
        def: "A system that anyone can interact with, without requiring approval, login, or KYC from a central authority. The APEX compound function is totally permissionless."
    },
    {
        term: "Smart Contract",
        def: "Self-executing code deployed on a blockchain. APEX is a suite of smart contracts that automate trading, depositing, and risk management without human intervention."
    }
];

export default function GlossaryPage() {
    return (
        <div className="docs-content flex flex-col gap-8">
            <div>
                <h1 className="text-[28px] font-medium mb-4">Glossary</h1>
                <p className="text-secondary mb-4">
                    DeFi is full of complex jargon. Here are straightforward definitions for the terms used throughout the APEX Protocol documentation.
                </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {terms.sort((a, b) => a.term.localeCompare(b.term)).map((item, idx) => (
                    <div key={idx} className="glass-card p-5 border border-[rgba(0,0,0,0.05)] hover:border-[rgba(0,0,0,0.1)] transition-colors">
                        <h3 className="text-[16px] font-semibold text-primary mb-2">{item.term}</h3>
                        <p className="text-sm text-secondary leading-relaxed">{item.def}</p>
                    </div>
                ))}
            </div>

            <div className="mt-6 text-sm text-secondary p-4 glass-card bg-[rgba(26,86,219,0.03)] border-l-4 border-l-accent">
                Did we miss a term? You can propose an addition by opening a pull request on our <a href="https://github.com/celvios/AsterDex" target="_blank" rel="noopener noreferrer" className="text-accent hover:underline font-medium">GitHub repository</a>.
            </div>
        </div>
    );
}
